### ISSUE TITLE
何时发布您的代码

### ISSUE THREAD

**Issue by zhaoguoqing12** [XiiZhao/cbn.pytorch#1]

**Comment by XiiZhao** [comment]
感谢您的关注，代码大概会在年后或者2月份发布~~

**Comment by zhaoguoqing12** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhe ***@***.***&gt;; 
发送时间: 2023年1月9日(星期一) 中午11:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiiZhao/cbn.pytorch] 何时发布您的代码 (Issue #1)





 
感谢您的关注，代码大概会在年后或者2月份发布~~

**Comment by 123cjjjj** [comment]
您好，还公布嘛？

**Comment by XiiZhao** [comment]
> 您好，还公布嘛？

感谢关注，目前还在整理中~~

**Comment by LDOUBLEV** [comment]
> > 您好，还公布嘛？
> 
> 感谢关注，目前还在整理中~~



感谢分享，有大概时间点吗

**Comment by XiiZhao** [comment]
> > > 您好，还公布嘛？
> > 
> > 
> > 感谢关注，目前还在整理中~~
> 
> 感谢分享，有大概时间点吗

感谢关注，代码已在重验证，后续还得等内部的审核和批准，静候~~ 谢谢！

**Comment by babble2** [comment]
请问快发布代码了么

**Comment by lgcy** [comment]
快一年了，这是不准备公布了？

**Comment by dhddxdhd** [comment]
> 快一年了，这是不准备公布了？
我也期待代码啥时候能开源，当初该工作投稿AAAI2023我还审过。

**Comment by AlphaNext** [comment]
> > 快一年了，这是不准备公布了？
> > 我也期待代码啥时候能开源，当初该工作投稿AAAI2023我还审过。

感谢大佬关注，源码马上走内审了

**Comment by XiiZhao** [comment]
> 快一年了，这是不准备公布了？
> 我也期待代码啥时候能开源，当初该工作投稿AAAI2023我还审过。

感谢大佬关注，代码走完内审就能公开了。

**Comment by XiiZhao** [comment]
代码已开源，如有问题可以提issue
